eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.22.130:8761/eureka/

spring:
  application:
    name: userui

server:
  port: 80
