eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.22.130:8761/eureka/

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/unit02
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root

server:
  port: 8882

